os: osx
sudo: false
dist: trusty
language: rust
cache: cargo
rust:
  - stable
branches:
  only:
  - master
script:
  - ./bin/mdbook build
deploy:
  provider: pages
  local-dir: book
  skip-cleanup: true
  github-token: $GITHUB_TOKEN
  keep-history: true
  on:
    branch: master
